FROM nginx:1.23
EXPOSE 80
WORKDIR /app
COPY ./docker/nginx.conf /etc/nginx/conf.d/vhost.conf
COPY ./2015.meteoriks.org /app/2015.meteoriks.org
COPY ./2016.meteoriks.org /app/2016.meteoriks.org
COPY ./2017.meteoriks.org /app/2017.meteoriks.org
COPY ./2018.meteoriks.org /app/2018.meteoriks.org
COPY ./2019.meteoriks.org /app/2019.meteoriks.org
COPY ./2020.meteoriks.org /app/2020.meteoriks.org
COPY ./2021.meteoriks.org /app/2021.meteoriks.org
